/**
 * Portfolio Loader
 * This script fetches the projects.json file generated by your Python scanner
 * and builds the HTML cards dynamically.
 */

const portfolioContainer = document.getElementById("repo-list");

async function loadPortfolio() {
    try {
        // 1. Fetch the data generated by your Python "Chef"
        const response = await fetch("./projects.json");
        
        if (!response.ok) {
            throw new Error("Could not find projects.json. Make sure to run your scanner.py first!");
        }

        const projects = await response.json();

        // 2. Clear the container (in case there's a loading spinner)
        portfolioContainer.innerHTML = "";

        // 3. Loop through each project and create the HTML
        projects.forEach(project => {
            const projectCard = document.createElement("div");
            projectCard.className = "repo-card";

            // Determine what image to show
            const imageHtml = project.image 
                ? `<img src="${project.image}" alt="${project.name} preview" class="project-img">`
                : `<div class="no-img-placeholder"><span>No Preview Available</span></div>`;

            // Create tag badges
            const tagsHtml = project.topics && project.topics.length > 0
                ? project.topics.map(tag => `<span class="tag-badge">${tag}</span>`).join("")
                : "";

            // Build the card structure
            projectCard.innerHTML = `
                <div class="card-inner">
                    ${imageHtml}
                    <div class="card-content">
                        <div class="card-header">
                            <h3>${project.name.replace(/-/g, ' ')}</h3>
                            <div class="stats">
                                <span>⭐ ${project.stars}</span>     
                            </div>
                        </div>

                        <p class="description">
                            ${project.description || "No description provided for this project."}
                        </p>
                        
                        <div class="tags-container">
                            ${tagsHtml}
                        </div>

                        <div class="card-footer">
                            <a href="${project.url}" target="_blank" class="view-btn">
                                View on GitHub
                                <img src="./assets/icons/arrow-right.svg" alt="arrow">
                            </a>
                            <span>${project.language || 'Code'}</span>
                        </div>
                    </div>
                </div>
            `;

            portfolioContainer.appendChild(projectCard);
        });

    } catch (error) {
        console.error("Portfolio Error:", error);
        portfolioContainer.innerHTML = `<p class="error-msg">Error loading projects: ${error.message}</p>`;
    }
}

// Start the engine
loadPortfolio();