/**
 * Portfolio Loader
 * This script fetches the projects.json file generated by your Python scanner
 * and builds the HTML cards dynamically.
 */

const portfolioContainer = document.getElementById("repo-list");
const headerImage = document.querySelector(".portfolio-header-image"); // Target the hero image

async function loadPortfolio() {
    try {
        const response = await fetch("./projects.json");
        
        if (!response.ok) {
            throw new Error("Could not find projects.json.");
        }

        const projects = await response.json();

        // --- NEW: Update Hero Image from GitHub ---
        // We check if the first project has an owner object (added by the GitHub API)
        // or we can simply use the GitHub avatar URL directly since the username is static.
        if (headerImage) {
            headerImage.src = `https://github.com/arcanesandip.png`;
        }
        // ------------------------------------------

        portfolioContainer.innerHTML = "";

        projects.forEach(project => {
            const projectCard = document.createElement("div");
            projectCard.className = "repo-card";

            const imageHtml = project.image 
                ? `<img src="${project.image}" alt="${project.name} preview" class="project-img">`
                : `<div class="no-img-placeholder"><span>No Preview Available</span></div>`;

            const tagsHtml = project.tags && project.tags.length > 0
                ? project.tags.map(tag => `<span class="tag-badge">${tag}</span>`).join("")
                : "";

            projectCard.innerHTML = `
                <div class="card-inner">
                    ${imageHtml}
                    <div class="card-content">
                        <div class="card-header">
                            <h3>${project.name.replace(/-/g, ' ')}</h3>
                            <div class="stats">
                                <span>⭐ ${project.stars}</span>     
                            </div>
                        </div>
                        

                        <div class="card-footer">
                            <a class="button no-underline" id="my-work-link" href="${project.url}" target="_blank" class="view-btn">
                                <span class="button-text">View my Github</span>
                                <img src="/arrow-right.svg" alt="arrow" class="right-arrow-icon" loading="lazy" />
                            </a>
                            <span>${project.language || 'Code'}</span>
                        </div>

                        <div class="tags-container">
                            ${tagsHtml}
                        </div>

                        <p class="description">
                            ${project.description || "No description provided for this project."}
                        </p>
                    </div>
                </div>
            `;

            portfolioContainer.appendChild(projectCard);
        });

    } catch (error) {
        console.error("Portfolio Error:", error);
        portfolioContainer.innerHTML = `<p class="error-msg">Error loading projects: ${error.message}</p>`;
    }
}

loadPortfolio();